### PR TITLE
bash bug fix, no arbitrary stop timeout, placeholder master during elect...

### PR DESCRIPTION
**Pull request by atorstling**
...ion period and more parameters.

Hi! These are my changes as we discussed at https://github.com/ClusterLabs/resource-agents/pull/212. I also added parameters for the the pid and socket file names, since I needed to override those for legacy reasons.

### CODE REVIEW

**Comment by phemmer** [comment]
Thanks

I'm really not sure why I had it timing out after 10 seconds during stop. Best let the resource timeout do its job :-)

Merged with a few minor tweaks. The 2 slightly significant ones were:
* `uname -n` instead of `crm_node -n`. This was mainly because of convention, as this is what other resource agents do. Plus the variable that this is being compared against is `meta_notify_master_uname`, so I think it's safer to actually use the uname.
* adjusted the log entry to a simple 'Setting master to...' message. Logging shouldn't explain why the app is doing what it's doing, just that it's doing it. *Why* is best left to documentation, or in this case, the source code.

**Comment by atorstling** [comment]
Hi Patrick,

Great that this gets merged! I agree with you on the logging. I used
crm_node for a reason, though. In the docs chapter 4.2 (
http://clusterlabs.org/doc/en-US/Pacemaker/1.1-plugin/html-single/Pacemaker_Explained/index.html#s-node-name)
you'll see that the node name is not always equal to uname, and that the
term uname is used internally for legacy reasons.

Thanks for contributing this script in the first place by the way, great
work!

Cheers,
Alex

**Comment by phemmer** [comment]
Thanks for that. I was looking for something similar to that. But it's kinda still unclear how that corresponds to the variable. Basically is `crm_node -n` a friendly name for the node, or is that uname variable guaranteed to be equal to it. I'll shoot an email off to the mailing list for clarification.

**Comment by phemmer** [comment]
So I decided to go and actually test it. I created a cluster and set a custom node name. Indeed, the custom name is what is passed in the `OCF_RESKEY_CRM_meta_notify_master_uname` name.

Thanks for pushing back on that :-P

I've updated the commit to keep the `crm_node -n`.

**Comment by atorstling** [comment]
Good call. I asked on IRC about what to use instead of uname, sice my
predecessor seemed to have had some issues with uname mismatches (judging
by code in our old adapted afdata script), but I never actually asked about
what the OCF variables were set to.

Oh and feel free to correct my comments, I have a tendency to write in
"yoda speak" at times, not a native english speaker...

Cheers

**Comment by atorstling** [comment]
Hello again!

I thought I saw a problem when the box was very weighed down. I think the
problem was that it took a while for redis to start after that the start
command was issued. This cased pacemaker to ban the node where redis was
starting. What would happen if starting redis would take time? Would we hit
the "start: Unknown error waiting for redis to start" case? Should we
account for "redis_client info" not being able to contact redis at all?

Thanks

**Comment by phemmer** [comment]
Sigh. Yup. I just went through the redis source code. It's standard practice for applications that daemonize themselfs to not do so until *after* they start accepting connections. Redis doesn't do this. It backgrounds itself before it's ready. I've opened https://github.com/antirez/redis/issues/2368 in regards to this issue. But since this problem is in current redis, the resource agent is going to be need to be modified to handle the situation. I'll put this on my todo list.

**Comment by atorstling** [comment]
Great thanks. If you give me a hint on how to do that I can work on it on
monday. What can we check for? Wait until redis-cli returns 0?

**Comment by phemmer** [comment]
There are a couple ways of doing it. Yes, an infinite loop that just runs `redis-cli` over and over, and lets the timout kill it if redis is dead (not a pretty solution), or taking off the `--daemonize` option and polling the socket (gives the advantage that if it fails to start, we know immediately (SIGCHLD), and don't have to wait for timeout).

**Comment by atorstling** [comment]
Not quite following your second approach.. You mean poll as in just wait
for the socket file to be created in a loop? And if redis crashes we have a
signal handler for chld which sets some variable so that the wait loop can
exit with "failed to start"?

Does taking of daemonize have other implications? What are the advantages
of using it?

**Comment by atorstling** [comment]
I thought about this some more. If I have understand things correctly,
waiting for SIGCHLD would mean enabling job control, and I'm not sure you
would want to do that, could that not have other implications? Besides, the
real fix is in Redis. I think it is more straightforward to add a
workaround in the meantime. So I went for the first ugly solution and
modded things to this (added the ping):

output="$(su "$REDIS_USER" -s /bin/sh -c "cd '$REDIS_RUNDIR'; exec
'$REDIS_SERVER' '$REDIS_CONFIG' --daemonize yes --unixsocket
'$REDIS_SOCKET' --pidfile '$REDIS_PIDFILE'" 2>&1)"

while true; do
   # wait for redis to start

   # Change: Redis daemonizes before accepting sockets

   # (See https://github.com/antirez/redis/issues/2368),
   # wait for socket to come up
   redis_client ping &> /dev/null || {
       sleep 1
       continue
   }

typeset -A info
while read line; do
[[ "$line" == "#"* ]] && continue
[[ "$line" != *":"* ]] && continue
IFS=':' read -r key value <<< "$line"
info[$key]="$value"
done < <(redis_client info)

if (( info[loading] == 0 )); then
break
elif (( info[loading] == 1 )); then
sleep "${info[loading_eta_seconds]}"
else
ocf_log err "start: Unknown error waiting for redis to start"
return $OCF_ERR_GENERIC
fi
done


----

I'll try to look into a Redis patch if I get the time. Perhaps you
could review it if I suggest something?


Cheers

**Comment by phemmer** [comment]
Sorry for the delay in getting back to this. I ended up just putting in a really simple workaround: https://github.com/phemmer/resource-agents/commit/3209751fdaa41838509a8be88a83b84bb5f649cb

Basically, on unknown error, if a redis process exists, keep waiting for it to start.

**Comment by atorstling** [comment]
Hi Patrick,

I hope I'm not bothering you. I've just noticed that master priority scores
aren't updated on promote. Is this intentional? I haven't really thought
much about how one ought to set master scores, but my intuition says that
one might want to re-set them on demote and promote. What are your thoughts?

Best regards,

Alexander

**Comment by phemmer** [comment]
That is somewhat deliberate.
Setting score has to be done carefully on a running cluster. One of the problems with some of the other proposed redis resource agents was that they were updating the master score incorrectly, and would cause pacemaker to go into a promote-demote loop, moving the master role around between the nodes.

Technically, there's no reason you couldn't constantly (or on certain events such as promote/demote) update the master score, but it needs to be done carefully.

**Comment by atorstling** [comment]
Ok. Makes sense. I'll think about what I need. I'm trying to recover from a
multi-master situation, and in this situation the promoted master keeps its
low slave score, so the "oldest" master, i.e the master which was _started_
in a master role wins. Have you considered this type of situation? afdatas
script seems to select the newest master, but I can't really make out if
it's on purpose or not

Oh and one more question: is there any particular reason for doing the link
check on demote? I'm seeing that master_link_status changes asynchronously,
so that check triggers an extra unneccesary demote. I thought I would
remove that code, since I don't really understand it's purpose. I figure
that you can't really do anything else but wait for the link to go up,
unless that code is supposed to re-initialize the slave connection if Redis
won't do that for you.

**Pull request merged**
